spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
  mvc:
    format:
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    username: 2055346449@qq.com
    password: ztomwtlilxbodaab
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:./file/
server:
  servlet:
    encoding:
      charset: utf-8

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/extend/*.xml

logging:
  level:
    com.example.mybatisplusdemo.mapper: debug
file-upload-path: ./file

#支付宝
alipay:
  appId: 9021000150603350
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCLWZvNciBB7Z1ZdCu9w5I7QnpbU2FuUn0PAAOqWPo7k1lEOeD2dy03SBuNulmg5b77y6rajJ0S5WjXwd3A2zV1RVy6wtFPGsdSAQZNSYhSeQQaJs/Rlk40mwsexHAwrk11zliHrP0s1nXzdpIWFVwwO0gpp7YkwIVcU+kC9Y84lCIMd/6BVxzNDjlIWWe5v1QZfqyVbdwXix48IChXbHeH1TP4OwSltV2HnaBHKSB7pQT0Qgzym8b+LUqBayylEBsay3JQrqCWbTQvLWvIqeDn/QeozdtdlelpW7IaqdZYqtO7Sxxlf3ZJlKgSMY7uBo0oJ4ewcdMuZDEhptXgccq7AgMBAAECggEAKJYg2uWyn4ElozhCxTKBFOF34cGXTxqXchb++k6QE2oHRefVrfNoKAHIhK8SC9relVfsm1r5JNfMgYrlm5Y9K7rYF01GyVNzWl8SBtCz89FrcHJ9dP3iKVA/HOb6BjO+O+Gtx1aLJtQP5qlSQzxVbXbWvcsrMekg7pNB+qqq3D9aSp3m4qHBDGAm8UgkkPj6z/GApmmvANuiMSToTolFFFd5aSMZRUFwwbfN7fheN8JasWSrZf7f+ICdHLHsLqJKOEDCkvTff5b4aWPeTrdCugjZPCTZTPKeh9R7Xlfo3wIRa1/It9/GMC0EO7nGbj34YcFpWm/UK3EkWn3bF9y0gQKBgQDRvx5GSxoKTnHzzjpSoxeJSkl4XWFq8n2QluSmPlCXG4lLfkGGeXi1zclyXDCukZDNPEyYF8rCYK8tX/BM0VwryZ23KKqQAcEf5Djospkjl71TJLvSOHPOFoPfn5M/QMG56zI3cukKAzC3SD/UJ7mQxRmoPd4FdfM7Twn9M3hNrQKBgQCqFGAjEW2708jcT6VVjm1EXAZqng1xN8s0osbcm1dEqpKJaDX5O4sc2NQvIL8zrtiHtWRwonUYeQFdU+ughFOulenG6J0H7/+o/tPKuRNLkOX2+Ga5S5lDGKZsusaq9QBFMYCy2Lk2Mz/UxomgfNqF8IyLK9sQhRWMvA02zUW3BwKBgDbTmWtQeFcXWEwdrTsqrJ1TkM7owe09w7rG5q/Z/CDzrrjQIPqwx+/mAfFlzcfj/xDW4UKkfXi/4yqeOGcsFsbPZe2ZsLQB8WSPuJyDCuq14GRaZso1vXeyhPgwc0IGgF1D8JVz8RyP5u0R8rVXSPdhviovOdj9kv3+1CKekKTlAoGBAIbhndRxz/qzXIoLx+zwBQu/h38qVTLCsq7NoLP3pd/Y/llmgddkN1DrTGsLp1bPhP0rB7qjvAVqgYCIO0eTaeH9FecfNtnCpZhab5BH8lttUFLqcFzm7Wbet61m+oM9xbcaKRys70Vio26U/TR/j7XFLVB5uUOCp7JyuHALnwwlAoGAe0fegNlpyPXZgyIYiJSceKlLWXeJH0AYq+75b1nbZprf7/FCe1DrPmKGLhwyOyeBtlXGxSVbQM5GfI7t9bgZfeF2ErkQ81zcwS1iQZLfYhrOnX8XsVyaFjo1omkM9mL5ubIE2lzjK9nPf4LhRqH8k+0mYQo5an6ILHSfmythcKw=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoEngoOIxJiPyZ73vQxd2z0bEvb/Da/sMhgJV4TW3zd1rrbAGW8asSa9gZUHmkGoGiNIW3oTT6Y1/WCGdsnAP5ETcnt75sD3p0mfK6toZGCNGd69EwzNazLDQNEmW/O7MVCL7dGOfODRJWRTIEEG+saeFPi6t68yGq7k0hK3pSUB+ds8VG2TvuJ9/wCdhv0MrIfe5duXbOmua0R01WFPy1o1jUW8YYP8fS4HX1z6hhRhF++u8nOR3waU5EFy8DWFerXY6lyG59SN5zjurOGkCfMB8oeJwxkmmqmVBPSp6KSGm5I/bWyO03rMU3dWU8zYS51Ox4nthr9yWRMZQHz+0RwIDAQAB
  notifyUrl:  http://y9346f86.natappfree.cc/alipay/notify
  returnUrl:   http://localhost:5174/user/orders